export const UNIVERSITY_LIST =
    [
        "Bakı Dövlət Universiteti (BDU)",
        "Bakı Ali Neft Məktəbi (BANM)",
        "Azərbaycan Dövlət Neft və Sənaye Universiteti (ADNSU)",
        "Azərbaycan Texniki Universiteti (AzTU)",
        "Azərbaycan Tibb Universiteti (ATU)",
        "Azərbaycan Dövlət İqtisad Universiteti (UNEC)",
        "Azərbaycan Dillər Universiteti (ADU)",
        "Azərbaycan Dövlət Pedaqoji Universiteti",
        "Azərbaycan Dövlət Rəssamlıq Akademiyası",
        "Azərbaycan Dövlət Mədəniyyət və İncəsənət Universiteti",
        "Azərbaycan Dövlət Aqrar Universiteti",
        "ADA Universiteti",
        "Xəzər Universiteti",
        "Qərb Kaspi Universiteti",
        "Azərbaycan Universiteti",
        "Bakı Mühəndislik Universiteti",
        "Odlar Yurdu Universiteti",
        "Azərbaycan Əməkdaşlıq Universiteti",
        "Azərbaycan Turizm və Menecment Universiteti",
        "Naxçıvan Dövlət Universiteti",
];

export const CATEGORY_LIST = [   {
        label: "🍽️ Yeyinti və İçki",
        options: [
                "Restoran",
                "Kafe",
                "Fast food",
                "Şirniyyat dükanı",
                "Çayxana",
                "Kofe dükanı",
                "Dondurma dükanı",
                "Suşi / Asiya mətbəxi",
                "Milli mətbəx",
        ],
},
        {
                label: "🛍️ Alış-veriş və Mağazalar",
                options: [
                        "Geyim mağazası",
                        "Ayaqqabı mağazası",
                        "Aksesuar / Bijuteriya",
                        "Parfümeriya / Kosmetika",
                        "Elektronika mağazası",
                        "Kitab mağazası",
                        "Oyuncaq mağazası",
                        "Supermarket / Market",
                        "Optika / Eynək dükanı",
                        "Mobil telefon / Aksesuar",
                ],
        },
        {
                label: "💼 Xidmətlər",
                options: [
                        "Bərbər / Gözəllik salonu",
                        "Avto yuma",
                        "Çap / Poliqrafiya xidməti",
                        "Tərcümə bürosu",
                        "Təmir xidməti",
                        "Fotoqraf xidmətləri",
                        "Nəqliyyat xidməti",
                        "İcarə xidmətləri",
                ],
        },
        {
                label: "🏥 Sağlamlıq və Gözəllik",
                options: [
                        "Xəstəxana",
                        "Klinika",
                        "Diş klinikası",
                        "Aptek",
                        "Fitness mərkəzi",
                        "Masaj / SPA",
                        "Dermatoloq / Kosmetoloq",
                ],
        },
        {
                label: "🎓 Təhsil və Kurslar",
                options: [
                        "Xarici dil kursları",
                        "İT kursları",
                        "Magistr / Sertifikat hazırlığı",
                        "Təlim mərkəzləri",
                        "Rəqs / Musiqi kursları",
                        "Uşaq inkişaf mərkəzləri",
                ],
        },
        {
                label: "🎭 Əyləncə və Hobbilər",
                options: [
                        "Kino",
                        "Teatr",
                        "Park / Əyləncə mərkəzi",
                        "Virtual oyun mərkəzləri",
                        "Qaçış otağı",
                        "Paintball / Lazer tag",
                ],
        },
        {
                label: "🏡 Digər",
                options: [
                        "Sığorta şirkətləri",
                        "Bank / Kredit təşkilatları",
                        "Onlayn xidmətlər",
                        "Turizm şirkətləri",
                        "Mehmanxana / Hostel / Airbnb",
                        "Qida çatdırılması platformaları",
                ],
        },
]
