export const UNIVERSITY_LIST = [
  'Bakı Dövlət Universiteti (BDU)',
  'Azərbaycan Dövlət Neft və Sənaye Universiteti (ADNSU)',
  'Azərbaycan Texniki Universiteti (AzTU)',
  'Azərbaycan Dövlət İqtisad Universiteti (UNEC)',
  'Azərbaycan Dillər Universiteti (ADU)',
  'Azərbaycan Dövlət Pedaqoji Universiteti',
  'Azərbaycan Memarlıq və İnşaat Universiteti',
  'Bakı Slavyan Universiteti',
  'Azərbaycan Dövlət Mədəniyyət və İncəsənət Universiteti',
  'Azərbaycan Dövlət Rəssamlıq Akademiyası',
  'Azərbaycan Milli Konservatoriyası',
  'Sumqayıt Dövlət Universiteti',
  'Lənkəran Dövlət Universiteti',
  'Gəncə Dövlət Universiteti',
  'Azərbaycan Texnologiya Universiteti',
  'Mingəçevir Dövlət Universiteti',
  'Naxçıvan Dövlət Universiteti',
  'Azərbaycan Tibb Universiteti (ATU)',
  'Azərbaycan Dövlət Bədən Tərbiyəsi və İdman Akademiyası',
  'Azərbaycan Dövlət Aqrar Universiteti',
  'Azərbaycan Dövlət Dəniz Akademiyası',
  'Milli Aviasiya Akademiyası',
  'Dövlət İdarəçilik Akademiyası',
  'Azərbaycan Turizm və Menecment Universiteti',
  'Bakı Ali Neft Məktəbi (BANM)',
  'ADA Universiteti',
  'Azərbaycan İlahiyyat İnstitutu',
  'Bakı Musiqi Akademiyası',

  'Xəzər Universiteti',
  'Qərb Kaspi Universiteti',
  'Azərbaycan Universiteti',
  'Bakı Mühəndislik Universiteti',
  'Odlar Yurdu Universiteti',
  'Azərbaycan Əməkdaşlıq Universiteti',
  'Bakı Avrasiya Universiteti',
  'Bakı Qızlar Universiteti',
  'Azərbaycan Biznes Universiteti',
  'Naxçıvan Universiteti',
  'Azərbaycan Əmək və Sosial Münasibətlər Akademiyası',

  'Fransız-Azərbaycan Universiteti (UFAZ)',
  'İtaliya-Azərbaycan Universiteti',
  'Türkiyə-Azərbaycan Universiteti',
  'Bakı Dövlət Universitetinin Moskva Dövlət Universiteti ilə birgə filialı',
  'Bakı Dövlət Universitetinin Seçenov adına Moskva Dövlət Tibb Universiteti ilə birgə filialı',

  'Azərbaycan Ali Hərbi Məktəbi',
  'Daxili İşlər Nazirliyinin Polis Akademiyası',
  'Dövlət Təhlükəsizlik Xidmətinin Akademiyası',
  'Daxili Qoşunların Ali Hərbi Məktəbi',
  'Dövlət Sərhəd Xidmətinin Akademiyası',
  'Fövqəladə Hallar Nazirliyinin Akademiyası',
  'Dövlət Gömrük Komitəsinin Akademiyası',
];

export const CATEGORY_LIST = [
  {
    label: '🍽️ Yeyinti və İçki',
    options: [
      'Restoran',
      'Kafe',
      'Fast food',
      'Şirniyyat dükanı',
      'Çayxana',
      'Kofe dükanı',
      'Dondurma dükanı',
      'Suşi / Asiya mətbəxi',
      'Milli mətbəx',
    ],
  },
  {
    label: '🛍️ Alış-veriş və Mağazalar',
    options: [
      'Geyim mağazası',
      'Ayaqqabı mağazası',
      'Aksesuar / Bijuteriya',
      'Parfümeriya / Kosmetika',
      'Elektronika mağazası',
      'Kitab mağazası',
      'Oyuncaq mağazası',
      'Supermarket / Market',
      'Optika / Eynək dükanı',
      'Mobil telefon / Aksesuar',
    ],
  },
  {
    label: '💼 Xidmətlər',
    options: [
      'Bərbər / Gözəllik salonu',
      'Avto yuma',
      'Çap / Poliqrafiya xidməti',
      'Tərcümə bürosu',
      'Təmir xidməti',
      'Fotoqraf xidmətləri',
      'Nəqliyyat xidməti',
      'İcarə xidmətləri',
    ],
  },
  {
    label: '🏥 Sağlamlıq və Gözəllik',
    options: [
      'Xəstəxana',
      'Klinika',
      'Diş klinikası',
      'Aptek',
      'Fitness mərkəzi',
      'Masaj / SPA',
      'Dermatoloq / Kosmetoloq',
    ],
  },
  {
    label: '🎓 Təhsil və Kurslar',
    options: [
      'Xarici dil kursları',
      'İT kursları',
      'Magistr / Sertifikat hazırlığı',
      'Təlim mərkəzləri',
      'Rəqs / Musiqi kursları',
      'Uşaq inkişaf mərkəzləri',
    ],
  },
  {
    label: '🎭 Əyləncə və Hobbilər',
    options: [
      'Kino',
      'Teatr',
      'Park / Əyləncə mərkəzi',
      'Virtual oyun mərkəzləri',
      'Qaçış otağı',
      'Paintball / Lazer tag',
    ],
  },
  {
    label: '🏡 Digər',
    options: [
      'Sığorta şirkətləri',
      'Bank / Kredit təşkilatları',
      'Onlayn xidmətlər',
      'Turizm şirkətləri',
      'Mehmanxana / Hostel / Airbnb',
      'Qida çatdırılması platformaları',
    ],
  },
];
