import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {Layout, Menu} from "antd";
import {Content, Header} from "antd/es/layout/layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const sections = [
        { key: "about", label: "Haqqımızda" },
        { key: "vision", label: "Vizyonumuz" },
        { key: "how", label: "Necə işləyir?" },
        { key: "contact", label: "Əlaqə" },
    ];

  return (
    <html lang="en">
      <body>
        <Layout>
            <Header
                className={'fixed w-full flex justify-between items-center py-0 px-[40px]'}>
                <Menu
                    theme="dark"
                    mode="horizontal"
                    className={'flex justify-center items-center w-screen'}
                    items={sections}
                />
            </Header>
            <Content>
                {children}
            </Content>
        </Layout>
      </body>
    </html>
  );
}
